[package]
name = "normalize"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = { version = "0.4.43", features = ["serde"] }
iso8601 = "0.6.3"
csv = "1.4.0"
anyhow = "1.0.102"